# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: nocodedb
    volumes:
     - /var/lib/postgresql/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
  
  engine:
    ports: 
      - "80:80"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://admin:admin@db/nocodedb"
    