version: '3.9'

services:
  engine:
    command: bash -c "alembic upgrade head && uvicorn engine.main:app --host 0.0.0.0 --port 80"
    restart: always

  frontend:
    ports:
      - "80:3000"
    restart: always
