services:
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  
  engine:
    build: 
      context: $ENGINE_PATH
    command: bash -c "alembic upgrade head && uvicorn engine.main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - $ENGINE_PATH/engine:/code/engine
    restart: on-failure
