version: '3.9'

services:
  engine:
    image: core-engine:local
    build: 
      context: $ENGINE_PATH
    command: bash -c "alembic upgrade head && uvicorn engine.main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - $ENGINE_PATH/engine:/code/engine

  frontend:
    image: frontend:local
    build:
      context: $FRONTEND_PATH 
      target: development
    ports:
      - "3000:3000"
    volumes:
      - $FRONTEND_PATH/src:/app/src
