version: '3.9'

services:
  trainer:
    image: trainer:local
    container_name: "trainer"
    restart: always
    build:
      context: $TRAINER_PATH
    volumes:
      - $TRAINER_PATH/trainer:/code/trainer
      - $ENGINE_PATH/upload:/code/upload

  engine:
    image: core-engine:local
    container_name: "engine"
    restart: always
    build: 
      context: $ENGINE_PATH
    volumes:
      - $ENGINE_PATH/engine:/code/engine
      - $ENGINE_PATH/alembic:/code/alembic
      - $ENGINE_PATH/upload:/code/upload

  frontend:
    image: frontend:local
    build:
      context: $FRONTEND_PATH 
    volumes:
      - $FRONTEND_PATH/src:/app/src
