version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: nocodedb
    volumes:
     - /var/lib/postgresql/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - pgadmin:/var/lib/pgadmin
  
  engine:
    image: ghcr.io/no-code-ds/core-engine:latest
    command: bash -c "alembic upgrade head && uvicorn engine.main:app --host 0.0.0.0 --port 80 --reload"
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://admin:admin@db/nocodedb"
    
  frontend:
    image: ghcr.io/no-code-ds/frontend:latest
    ports:
      - "80:80"
    environment:
      BACKEND_URL: "engine"

volumes:
  pgadmin:
