version: '3.9'

services:
  trainer:
    restart: on-failure:20
    command: bash -c "cd trainer && python -u consumer.py"

  engine:
    command: bash -c "alembic upgrade head && uvicorn engine.main:app --host 0.0.0.0 --port 8000"
    restart: always

  frontend:
    restart: always
